### PR TITLE
Fix build directory structure to use index.html for each route

### PR DESCRIPTION
**Pull request by TeeKz**
Change the build structure to make the page URL appear as '/about' instead of '/about.html'. Structured like

├── /about/                   
│   ├── /index.html              
├── /blog/                       
│   ├── /post-one/                  
│   │   ├── /index.html                  
│   ├── /post-two/                  
│   │   ├── /index.html                
│   ├── /index.html             
├── /404/   
│   ├── /index.html                     
├── /500/    
│   ├── /index.html                  
├── /index.html

### CODE REVIEW

**Comment by koistya** [comment]
I guess this is needed to make the files structure to be compatible with Amazon S3? I guess it doesn't yet support requesting HTML pages without `.html` part. If so, that might be a good fix!

**Comment by TeeKz** [comment]
More pulling on my experience with Jekyll. Seems to make sense to me.

**Comment by TeeKz** [comment]
Why add the complexity of making it configurable? This should work in GitHub Pages as well as any other webserver. 

What about other static generators? I've really only used Jekyll, which is fully supported by GitHub and GitHub Pages. Jekyll goes the way of using lots of folders and index.html.

**Comment by koistya** [comment]
@TeeKz oh, good to know. Maybe you right and it's better to generate a folder for each `index.html` page to make the site work on all platforms.

**Pull request closed without merging**
