### PR TITLE
Integrate react-routing 

### PR DESCRIPTION
**Pull request by t-kelly**
As discussed in https://github.com/koistya/react-static-boilerplate/issues/9

- Add react-routing in the same manor done in react-starter-kit
- Adjust routes-loader.js to create routes with react-routing formatting
- Automated routes created in src/router.js
- Create '/pages' directory used for site structure and route creation
- Match file structure to react-starter-kit

### CODE REVIEW

**Comment by Frenzzy** [comment]
wow, awesome!

**Comment by koistya** [comment]
This is really cool! I just need some time to review everything..

**Comment by TeeKz** [comment]
Any progress on checking this over for merging? Going to continue working on some other parts this week.

**Comment by koistya** [comment]
@t-kelly I have partially copied over your modifications, but not all yet..

**Comment by t-kelly** [comment]
:+1:

**Pull request closed without merging**
