### PR TITLE
Fixed directory routes

### LINKED ISSUE #37: markup being generated is different on the client or server warning
Running fresh project generated from version 0.2.9, then open http://localhost:3000/blog give warning: 

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) =".23cjq30ov7k.1.0">Not Found</h1><p dat
 (server) =".23cjq30ov7k.1.0">Blog</h1><p data-rea

The browser rendering http://localhost:3000/404 instead of the pages/blog/index.js.

### PR DESCRIPTION
**Pull request by WillemLabu**
Fixes #37

~/tools/lib/routes-loader.js now renders the trailing
slash at the end of directories. This fixes directory
browsing with no "filename".

### CODE REVIEW

**Comment by dvdplm** [comment]
Doesn't this clash with the logic where `/foo/bar.js` becomes a `/foo/bar` route? Wouldn't it turn `/foo/bar` into `/foo/bar/` too?

**Comment by WillemLabu** [comment]
Nope, doesn't break the file-specific routes, but it does mean you have to link to directories **with** a trailing slash:
```jsx
<a href='/blog/' onClick={Link.handleClick}>Blog</a>
```

**Comment by koistya** [comment]
I think it would be nice to use URLs *without* a trailing slash for all the URLs, e.g. `<a href="/blog/some-article">`. Plus make sure that web pages with trailing slashes redirect a user to corresponding pages without slashes, e.g. `/blog/some-article/` ->`/blog/some-article'.

@WillemLabu, it seems to me like the majority of the websites prefer using URLs without a trailing slash. Checking airbnb.com, medium.com...

**Comment by dvdplm** [comment]
@koistya the trouble I'm seeing here is that when I reload a page `/foo/bar` the browser (Chrome) adds the trailing slash and loads `/foo/bar/` which is a 404 without double routes (or some other devilry).

**Comment by WillemLabu** [comment]
Hey @koistya,

Apologies for not getting to this sooner - it's been a busy time.

There is probably a better way of doing this, but please have a look at (this commit)[https://github.com/WillemLabu/react-static-boilerplate/commit/baf7f2f78a7ad8c038363c3175c8eaaf7164f900], and let me know what your thoughts are.

Like @dvdplm mentions, I'm creating double routes for each directory found in `/pages`.

e.g.: `/blog` as well as `/blog/`

Even though the former should be used with `<a>` components, the latter is required because hitting refresh in the browser will cause the 404 page to load.

**Comment by koistya** [comment]
Thanks for the PR! I think that this issue had been solved, check the latest version from `master` branch.

**Pull request closed without merging**
