### PR TITLE
Integrate CSS Modules

### PR DESCRIPTION
**Pull request by kaploink**
As per todo list in https://gitter.im/koistya/react-static-boilerplate :)

Using https://github.com/webpack/css-loader#css-modules

Some styles should be refactored; leaving as separate change

### CODE REVIEW

**Comment by koistya** [comment]
@kaploink thanks! I need some time to review and make final tweaks before merging.

**Comment by kaploink** [comment]
No probs - first OSS PR :)

Fyi, the "s." convention is not standardised, but find it keeps the markup much cleaner than "styles.".  Similarly use "cx" for classnames helper, as react originally did for its equivalent.  E.g.:

```javascript
import React from 'react';
import s from "./PeopleViewed.scss";
import cx from "classnames";

export default class PeopleViewed extends React.Component {
    render() {
        return
            <div className={cx(s.this, "n_columns n_columns--space-5")}>
                <div className={s.views}>{this.props.views}</div>
                <div className={s.text}>viewed this car</div>
            </div>
    }
}

PeopleViewed.propTypes = {
    views: React.PropTypes.number.isRequired
};
```

**Comment by kaploink** [comment]
Just noticed cssnext's `:root`.  To avoid confusion perhaps we should change from `.root` (CSS Module example code convention) to `.this` (what I've been using).

**Comment by koistya** [comment]
@kaploink doesn't ESLint complain about these short var names?

**Comment by kaploink** [comment]
Hmm, I see.

Well given the purpose of that ESLint rule is to improve readability, I guess the question should be which option you find more readable, and whether this a valid exception to its normal script variable focus (e.g. `for (var i = 0; i < 10; i++)`).

If you do prefer it for readability, a solution could be renaming to `_s` and adding an ESLint exception for that variable name.

The convention is partly in response to a common criticism of BEM/OOCSS/etc - that they clutter the markup with long repetitive prefixes.

**Comment by koistya** [comment]
@kaploink thanks for the suggestion! I'm using this convention all over the place now in both [RSK](https://github.com/kriasoft/react-starter-kit) and [RSB](https://github.com/koistya/react-static-boilerplate) projects. What do you think about this CSS Modules configuration, looks legit?

[/tools/webpack.config.js#L81-L95](https://github.com/koistya/react-static-boilerplate/blob/34525ee8202673062d6c96eb6348ec7f75d0325d/tools/webpack.config.js#L81-L95)
[/tools/webpack.config.js#L115-L129](https://github.com/koistya/react-static-boilerplate/blob/34525ee8202673062d6c96eb6348ec7f75d0325d/tools/webpack.config.js#L115-L129)

**Comment by kaploink** [comment]
@koistya ha, great, glad you approve!  I actually switched to using _s because of this discussion :) .

Tbh I don't actually use CSS modules per se - instead just use what it was built upon: [css loader's local scope](https://github.com/webpack/css-loader#local-scope)...

Local scope is what solved the core problem of scoping using the `:local` keyword (and `:global` to get back), which CSS modules extends by:
1. assuming all imported files are intended to be local
2. adding rich composition capability via imports
3. specifying conventions / best practices for modularising styles

For 1 I prefer leaving it at global by default, as that `:local` is a nice brief indicator that there's something special going on, and it allows importing non-localised 3rd party/legacy scss/css as is (not sure what the css modules solution for this is).

For 2 & 3 I prefer keeping the scss really basic, and instead doing component composition just in react.  All layout/structure is specified in markup (flex, alignment, margin, padding, gutters, widths, heights, wrapping, etc - I use a Box component similar to React Native's View) so there's not much left for css to handle, and I'm gradually doing more css in js partly because of Material UI.


Also, re. https://github.com/kriasoft/react-starter-kit/blob/master/src/components/Header/Header.scss for example, I'd still nest all those selectors - to make the hierarchy clearer and avoid the brand/banner prefixes.  If using global by default (not css modules) and nested selector tree under root, to make local you'd just add `:local ` before the `.root`.

**Pull request closed without merging**
